### ISSUE TITLE
For Glibc users: Glibc2.25 breaks compilation

### ISSUE THREAD

**Issue by cpmachado** [jtvaughan/ptar#15]
@jtvaughan 
In case you are assuming your users are using glibc.
These functions : makedev(), major(), minor() 
Are no longer exposed by sys/types.h,
because it no longer includes sys/sysmacros.h

[Since 2.25](https://sourceware.org/ml/libc-alpha/2017-02/msg00079.html)

Solution, just include the header. 
I can patch it, and ask for a pull request, but I trust your judgement more in this. 

Currently my machine is running glibc 2.29

In case it isn't a priority, a notice might be useful. Many may want to experiment with ptar and not be aware of how to fix it.

Thank you for your attention.

**Comment by cpmachado** [comment]
Notice that these functions are not defined in POSIX, thus it's dealers choice.

**Comment by forskning** [comment]
http://nurmi-labs.blogspot.com/2017/04/p9p.html

Regarding glibc 2.20 see the above.

Any opinion about creating (series) releases for this repository?

0.x current repos' code for glibc <2.20
1.x for glibc ==2.20 to <2.25
2.x for >=glibc 2.25

For 1.x the depracated _BSD_SOURCE macro could be addressed.

@cpmachado 

slackware-14.2 (my machine) is running glibc 2.23
slackware-current (the development version) runs glibc 2.29

**Comment by cpmachado** [comment]
@forskning 
This is @jtvaughan  decision. I just wanted to give a heads up.

My opinion regarding the matter is that a a release per each one of those makes little sense, for once the compilation flag is a configurable aspect.

The header file missing is to worry about, if someone is just trying for fun, and isn't able do anything and isn't crazy about going change the code. Even though it just adding a header file.
The thing is those functions were just tacitly included by the header sys/types.h, being declared in sys/sysmacros.h. Now they are not.

My fork has those changes.
I investigated the matter, and it's just the classic glibc randomly changing parts of their sys libs.

**Comment by forskning** [comment]
https://github.com/cpmachado/ptar/commit/00b3d5d64a3030eeff80a352648faeeb9b51b501

@cpmachado the patch in your fork didn't modify install.sh which also contains the deprecated -D_BSD_SOURCE macro

FWIW, one advantage of having "releases" is if one creates an installable package from the code.

In that scenario one would be cognisant that a certain release "works" with a certain version of a package creation script.

**Comment by cpmachado** [comment]
I'm going a different way with it, I'm writing a manpage and even changing the command.
It will be named pstar as not to collide with ptar from perl-core.

**Comment by forskning** [comment]
https://github.com/jtvaughan/ptar/issues/15#issuecomment-491089817

FWIW, here are some reference webpages.

https://help.github.com/en/articles/getting-the-download-count-for-your-releases

https://developer.github.com/v3/repos/releases/

https://github.com/jtvaughan/ptar/issues/15#issuecomment-491224177

Yes, there is an executable ptar script (or ptar.bat file) accompanying Perl installations.

I guess you'll be closing this issue then.
