### ISSUE TITLE
char should be cast to unsigned char

### ISSUE THREAD

**Issue by BitPuffin** [jtvaughan/ptar#7]
Hello!

Nice project, I like it very much. I tried running this on windows in cygwin. At first it didn't build, but then I cast the parameters to functions such as isalnum etc to unsigned char and after that it built. After that I am glad to report that it seems to work flawlessly :dancer:

If you don't beat me to it I will probably wrap it up in a pull request eventually but I thought I'd post it as an issue for now.

Cheers!

**Comment by joodan-van-github** [comment]
Hi BitPuffin,

Thanks for telling me about that.  I've committed code that should fix the issue you described.  Please let me know when you test it so I can close this issue.

Thanks,
Jordan
